### ISSUE TITLE
Rename extensions to match the new community policies and match Quarkus Platform

### ISSUE THREAD

**Issue by ricardozanini** [apache/incubator-kie-kogito-images#1749]
Since we are now renaming our extensions to match our new policies and projects, we should update the references in this repository. For example: 

https://github.com/apache/incubator-kie-kogito-images/blob/main/modules/kogito-swf/builder/build-config/module.yaml#L30

**Comment by wmedvede** [comment]
The renaming also apply to swf-devmode image, and also consider that the serverless workflows dev UI was now renamed to:
        <dependency>
            <groupId>org.kie.kogito</groupId>
            <artifactId>sonataflow-quarkus-devui</artifactId>
        </dependency>
